name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      databend:
        image: datafuselabs/databend
        env:
          QUERY_DEFAULT_USER: databend
          QUERY_DEFAULT_PASSWORD: databend
          MINIO_ENABLED: true
        ports:
          - 8000:8000
          - 9000:9000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Service Running
        run: |
          sleep 30
          cid=$(docker ps -a | grep databend | cut -d' ' -f1)
          docker logs ${cid}
          curl -u databend:databend  --request POST localhost:8000/v1/query --header 'Content-Type:application/json' --data-raw '{"sql":"select 1"}'

      - name: Run Maven clean deploy with release profile
        run: mvn clean test
